# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2c5155268dedbcfe8aa1ac116f11535227c9e02d7d7a576b02eb8720cbb9e60e584c94ad06793314a91fe454dd5b1af626454d13c194830675ecf2d6cd9926d8

test:
  secret_key_base: a245a0776aef868ca7dde5968973756a0fee2043cf71476821e705f99b3050ac2f3a0fb2d8516fabcb8b306b96e6cd9dae3e21c2bf047ac4e52f8ce489ac4bf3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
